name: Secrets

on: push

jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Secrets
        run: |
          echo "$DEVOPS"
        env: 
          DEVOPS: ${{ secrets.SECRET_TOKEN }}
          
